name: 'openmodelica-library-testing'
description: 'Setup OpenModelicaLibraryTesting scripts and run them on Modelica package and publishes results.'
author: 'Andreas Heuermann'

# Action inputs
inputs:
  package-name:
    description: 'Name of Modelica package to test.'
    required: true
  package-version:
    description: 'Version of Modelica package to test.'
    required: true
  modelica-file:
    description: 'Path to Modelica file containing package to test. E.g to package.mo'
    required: true
    default: 'package.mo'
  dependencies:
    description: 'Modelica library dependencies to install with the OpenModelica package manager.'
    required: true
    default: ''
  omc-version:
    description: 'Version of OpenModelica to use for testing'
    required: true
    default: 'stable'
  reference-files-dir:
    description: 'Path to reference files'
    required: true
    default: ''
  reference-files-format:
    description: 'File extension of result files. Allowed values are "mat" and "csv".'
    required: true
    default: 'mat'
  reference-files-delimiter:
    description: 'Character to separate model names in reference files. E.g. for Modelica.Blocks.Examples.PID_Controller.mat it would be "."'
    required: true
    default: '.'
  GITHUB_TOKEN:
    description: 'Value of secrets.GITHUB_TOKEN to authenticate and write comments in PRs.'
    required: true
  publish-gh-pages:
    description: 'Push results to gh-pages branch.'
    required: true
    default: true
  gh-pages-ref:
    description: 'Branch GitHub Pages deploys from, e.g. `gh-pages`'
    required: true
    default: 'gh-pages'
  pages-root-url:
    description: 'Root url GitHub Pages deploys to, e.g. https://<GitHub User>.github.io/<Repository>'

# Action outputs
outputs:
  simulation-tests-passing:
    description: 'True if all simulation tests are passing'
    value: ${{ steps.summary.outputs.simulation-tests-passing }}
  n-simulation-passing:
    description: 'Number of successful simulation tests'
    value: ${{ steps.summary.outputs.n-simulation-passing }}
  verification-tests-passing:
    description: 'True if all verification tests are passing'
    value: ${{ steps.summary.outputs.verification-tests-passing }}
  n-verification-passing:
    description: 'Number of successful verification tests'
    value: ${{ steps.summary.outputs.n-verification-passing }}

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'check-square'
  color: 'blue'
